import {
  STANDARD_BIPED_MOTION,
  STANDARD_RIG,
  type VoxelCharacterDefinition,
} from "./lib/voxel-character-kit";

export type CharacterStatus = "ready" | "planned";

export type CharacterCatalogEntry = VoxelCharacterDefinition & {
  name: string;
  englishName: string;
  role: string;
  referenceImage: string;
  accent: string;
  status: CharacterStatus;
  bodyType: string;
  rigLabel: string;
  note: string;
};

const standardBipedRig = {
  primaryArm: [STANDARD_RIG.primaryArm],
  secondaryArm: [STANDARD_RIG.secondaryArm],
  leftLeg: [STANDARD_RIG.leftLeg],
  rightLeg: [STANDARD_RIG.rightLeg],
  locomotionExtras: [STANDARD_RIG.locomotionPrefix],
};

export const CHARACTERS: CharacterCatalogEntry[] = [
  {
    id: "sobaya",
    name: "そば屋",
    englishName: "SOBAYA",
    role: "POWER TYPE",
    referenceImage: "/characters/sobaya.jpg",
    accent: "#ffb21a",
    status: "ready",
    bodyType: "大型・二足",
    rigLabel: "BIPED / 4 PIVOTS",
    note: "仮面とビールジョッキを維持。歩行とスマッシュを実機確認できます。",
    modelUrl: "/models/sobaya.glb?v=rear-turnaround-1",
    scale: 1.52,
    rotationY: Math.PI,
    rig: standardBipedRig,
    motion: { ...STANDARD_BIPED_MOTION },
  },
  {
    id: "takosan",
    name: "たこさん",
    englishName: "TAKOSAN",
    role: "TENTACLE TYPE",
    referenceImage: "/characters/takosan.png",
    accent: "#8c7bff",
    status: "ready",
    bodyType: "触手・浮遊",
    rigLabel: "TENTACLED / 8 PIVOTS",
    note: "正方形頭、装飾ローブのテクスチャ、人間の腕2本、6本の段状触手を維持。",
    modelUrl: "/models/takosan.glb?v=square-head-3",
    scale: 1.3,
    rotationY: Math.PI,
    rig: {
      primaryArm: [STANDARD_RIG.primaryArm],
      secondaryArm: [STANDARD_RIG.secondaryArm],
      locomotionExtras: [STANDARD_RIG.locomotionPrefix],
    },
    motion: {
      ...STANDARD_BIPED_MOTION,
      strideAngle: 0,
      extraLocomotionAngle: 0.34,
      walkFrequency: 8.2,
    },
  },
  {
    id: "tokun",
    name: "とーくん",
    englishName: "TOKUN",
    role: "MUSIC TYPE",
    referenceImage: "/characters/tokun.jpg",
    accent: "#ff9838",
    status: "ready",
    bodyType: "ふくよか・二足",
    rigLabel: "BIPED / 4 PIVOTS",
    note: "アロハ・麦わら帽子・レイを維持。ウクレレはプライマリアーム固定でスマッシュ。",
    modelUrl: "/models/tokun.glb?v=initial-1",
    scale: 1.42,
    rotationY: Math.PI,
    rig: standardBipedRig,
    motion: {
      ...STANDARD_BIPED_MOTION,
      walkFrequency: 10.0,
      strideAngle: 0.44,
    },
  },
  {
    id: "yotan",
    name: "よーたん",
    englishName: "YOTAN",
    role: "ROCK TYPE",
    referenceImage: "/characters/yotan.jpg",
    accent: "#ffd84a",
    status: "ready",
    bodyType: "細身・二足",
    rigLabel: "BIPED / 4 PIVOTS",
    note: "金髪ロング・黒レザー・丸サングラスを維持。ギターはプライマリアーム固定。",
    modelUrl: "/models/yotan.glb?v=initial-1",
    scale: 1.34,
    rotationY: Math.PI,
    rig: standardBipedRig,
    motion: {
      ...STANDARD_BIPED_MOTION,
      walkFrequency: 12.5,
      windupAngle: 0.72,
    },
  },
  {
    id: "fukuchan",
    name: "福ちゃん",
    englishName: "FUKUCHAN",
    role: "SPONSOR TYPE",
    referenceImage: "/characters/fukuchan.jpg",
    accent: "#ff7ab0",
    status: "ready",
    bodyType: "細身・二足",
    rigLabel: "BIPED / 4 PIVOTS",
    note: "紺ロングコート・白グラフィックT・名札とSPONSORストラップ・ピンク頬を維持。",
    modelUrl: "/models/fukuchan.glb?v=initial-1",
    scale: 1.36,
    rotationY: Math.PI,
    rig: standardBipedRig,
    motion: { ...STANDARD_BIPED_MOTION },
  },
  {
    id: "yametaro",
    name: "無職やめ太郎",
    englishName: "YAMETARO",
    role: "COMEDY TYPE",
    referenceImage: "/characters/yametaro.jpg",
    accent: "#ff68aa",
    status: "ready",
    bodyType: "小型・二足",
    rigLabel: "BIPED / 4 PIVOTS",
    note: "正方形頭と横分け髪。黒目なしの純白レンズ、ピンク頬、襟込みシャツをテクスチャ化。",
    modelUrl: "/models/yametaro.glb?v=rear-turnaround-1",
    scale: 1.2,
    rotationY: Math.PI,
    rig: standardBipedRig,
    motion: {
      ...STANDARD_BIPED_MOTION,
      strideAngle: 0.4,
      walkFrequency: 13.5,
      windupAngle: 0.92,
      secondaryArmRecoil: 0.34,
    },
  },
  {
    id: "okayaman",
    name: "窓際王おかやまん",
    englishName: "OKAYAMAN",
    role: "REMOTE TYPE",
    referenceImage: "/characters/okayaman.jpg",
    accent: "#6ac4ff",
    status: "ready",
    bodyType: "スクリーン・据置",
    rigLabel: "SCREEN / 1 PIVOT",
    note: "穏やかな笑顔のままスクリーン越しにリモート出演。スマッシュは画面全体の前傾おじぎ。",
    modelUrl: "/models/okayaman.glb?v=initial-1",
    scale: 1.24,
    rotationY: Math.PI,
    rig: {
      primaryArm: [STANDARD_RIG.primaryArm],
      locomotionExtras: [STANDARD_RIG.locomotionPrefix],
    },
    motion: {
      ...STANDARD_BIPED_MOTION,
      strideAngle: 0,
      primaryArmWalk: 0.05,
      walkFrequency: 6.0,
      windupAngle: 0.30,
      impactAngle: -0.85,
      rootLeanAngle: 0.05,
    },
  },
  {
    id: "yumemin",
    name: "ゆめみん",
    englishName: "YUMEMIN",
    role: "MASCOT TYPE",
    referenceImage: "/characters/yumemin.jpg",
    accent: "#62aede",
    status: "ready",
    bodyType: "浮遊・マスコット",
    rigLabel: "MASCOT / 2 PIVOTS",
    note: "青い体・点目・白いお尻・自由に動く鼻を維持。木槌のBONKがスマッシュ。",
    modelUrl: "/models/yumemin.glb?v=initial-1",
    scale: 1.5,
    rotationY: Math.PI,
    rig: {
      primaryArm: [STANDARD_RIG.primaryArm],
      locomotionExtras: [STANDARD_RIG.locomotionPrefix],
    },
    motion: {
      ...STANDARD_BIPED_MOTION,
      strideAngle: 0,
      extraLocomotionAngle: 0.42,
      walkFrequency: 8.5,
      windupAngle: 0.85,
    },
  },
];
